/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.2-Docker-3.4.1 (4.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// AsnRange : Adds support for custom fields and tags.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AsnRange {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "display_url")]
    pub display_url: String,
    #[serde(rename = "display")]
    pub display: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "rir")]
    pub rir: Box<crate::models::BriefRir>,
    #[serde(rename = "start")]
    pub start: i64,
    #[serde(rename = "end")]
    pub end: i64,
    #[serde(
        rename = "tenant",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tenant: Option<Option<Box<crate::models::BriefTenant>>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::NestedTag>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "created", deserialize_with = "Option::deserialize")]
    pub created: Option<String>,
    #[serde(rename = "last_updated", deserialize_with = "Option::deserialize")]
    pub last_updated: Option<String>,
    #[serde(rename = "asn_count")]
    pub asn_count: i32,
}

impl AsnRange {
    /// Adds support for custom fields and tags.
    pub fn new(
        id: i32,
        url: String,
        display_url: String,
        display: String,
        name: String,
        slug: String,
        rir: crate::models::BriefRir,
        start: i64,
        end: i64,
        created: Option<String>,
        last_updated: Option<String>,
        asn_count: i32,
    ) -> AsnRange {
        AsnRange {
            id,
            url,
            display_url,
            display,
            name,
            slug,
            rir: Box::new(rir),
            start,
            end,
            tenant: None,
            description: None,
            tags: None,
            custom_fields: None,
            created,
            last_updated,
            asn_count,
        }
    }
}
