/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.3 (4.6)
 *
 * Generated by: https://openapi-generator.tech
 */

/// AvailableIpRequestRequest : Request payload for creating IP addresses from the available-ips endpoint.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AvailableIpRequestRequest {
    #[serde(rename = "prefix_length", skip_serializing_if = "Option::is_none")]
    pub prefix_length: Option<i32>,
}

impl AvailableIpRequestRequest {
    /// Request payload for creating IP addresses from the available-ips endpoint.
    pub fn new() -> AvailableIpRequestRequest {
        AvailableIpRequestRequest {
            prefix_length: None,
        }
    }
}
