/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.2-Docker-3.4.1 (4.4)
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AvailablePrefix : Representation of a prefix which does not exist in the database.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AvailablePrefix {
    #[serde(rename = "family")]
    pub family: i32,
    #[serde(rename = "prefix")]
    pub prefix: String,
    #[serde(rename = "vrf", deserialize_with = "Option::deserialize")]
    pub vrf: Option<Box<crate::models::BriefVrf>>,
}

impl AvailablePrefix {
    /// Representation of a prefix which does not exist in the database.
    pub fn new(family: i32, prefix: String, vrf: Option<crate::models::BriefVrf>) -> AvailablePrefix {
        AvailablePrefix {
            family,
            prefix,
            vrf: if let Some(x) = vrf {Some(Box::new(x))} else {None},
        }
    }
}


