/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.2-Docker-3.4.1 (4.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// AvailableIp : Representation of an IP address which does not exist in the database.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AvailableIp {
    #[serde(rename = "family", skip_serializing_if = "Option::is_none")]
    pub family: Option<i32>,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(
        rename = "vrf",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub vrf: Option<Option<Box<crate::models::BriefVrf>>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl AvailableIp {
    /// Representation of an IP address which does not exist in the database.
    pub fn new() -> AvailableIp {
        AvailableIp {
            family: None,
            address: None,
            vrf: None,
            description: None,
        }
    }
}
