/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.2-Docker-3.4.1 (4.4)
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BackgroundTask {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "origin")]
    pub origin: String,
    #[serde(rename = "func_name")]
    pub func_name: String,
    #[serde(rename = "args")]
    pub args: Vec<serde_json::Value>,
    #[serde(rename = "kwargs")]
    pub kwargs: ::std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "result")]
    pub result: String,
    #[serde(rename = "timeout")]
    pub timeout: i32,
    #[serde(rename = "result_ttl")]
    pub result_ttl: i32,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "enqueued_at")]
    pub enqueued_at: String,
    #[serde(rename = "started_at")]
    pub started_at: String,
    #[serde(rename = "ended_at")]
    pub ended_at: String,
    #[serde(rename = "worker_name")]
    pub worker_name: String,
    #[serde(rename = "position")]
    pub position: i32,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "meta")]
    pub meta: ::std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "last_heartbeat")]
    pub last_heartbeat: String,
    #[serde(rename = "is_finished")]
    pub is_finished: bool,
    #[serde(rename = "is_queued")]
    pub is_queued: bool,
    #[serde(rename = "is_failed")]
    pub is_failed: bool,
    #[serde(rename = "is_started")]
    pub is_started: bool,
    #[serde(rename = "is_deferred")]
    pub is_deferred: bool,
    #[serde(rename = "is_canceled")]
    pub is_canceled: bool,
    #[serde(rename = "is_scheduled")]
    pub is_scheduled: bool,
    #[serde(rename = "is_stopped")]
    pub is_stopped: bool,
}

impl BackgroundTask {
    pub fn new(id: String, url: String, description: String, origin: String, func_name: String, args: Vec<serde_json::Value>, kwargs: ::std::collections::HashMap<String, serde_json::Value>, result: String, timeout: i32, result_ttl: i32, created_at: String, enqueued_at: String, started_at: String, ended_at: String, worker_name: String, position: i32, status: String, meta: ::std::collections::HashMap<String, serde_json::Value>, last_heartbeat: String, is_finished: bool, is_queued: bool, is_failed: bool, is_started: bool, is_deferred: bool, is_canceled: bool, is_scheduled: bool, is_stopped: bool) -> BackgroundTask {
        BackgroundTask {
            id,
            url,
            description,
            origin,
            func_name,
            args,
            kwargs,
            result,
            timeout,
            result_ttl,
            created_at,
            enqueued_at,
            started_at,
            ended_at,
            worker_name,
            position,
            status,
            meta,
            last_heartbeat,
            is_finished,
            is_queued,
            is_failed,
            is_started,
            is_deferred,
            is_canceled,
            is_scheduled,
            is_stopped,
        }
    }
}


