/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.2-Docker-3.4.1 (4.4)
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Branch : Adds support for custom fields and tags.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Branch {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "display")]
    pub display: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Box<crate::models::BranchStatus>>,
    #[serde(rename = "owner")]
    pub owner: Box<crate::models::BriefUser>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "schema_id")]
    pub schema_id: String,
    #[serde(rename = "last_sync", deserialize_with = "Option::deserialize")]
    pub last_sync: Option<String>,
    #[serde(rename = "merged_time", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub merged_time: Option<Option<String>>,
    #[serde(rename = "merged_by")]
    pub merged_by: Box<crate::models::BriefUser>,
    #[serde(rename = "comments", skip_serializing_if = "Option::is_none")]
    pub comments: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::NestedTag>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "created", deserialize_with = "Option::deserialize")]
    pub created: Option<String>,
    #[serde(rename = "last_updated", deserialize_with = "Option::deserialize")]
    pub last_updated: Option<String>,
}

impl Branch {
    /// Adds support for custom fields and tags.
    pub fn new(id: i32, url: String, display: String, name: String, owner: crate::models::BriefUser, schema_id: String, last_sync: Option<String>, merged_by: crate::models::BriefUser, created: Option<String>, last_updated: Option<String>) -> Branch {
        Branch {
            id,
            url,
            display,
            name,
            status: None,
            owner: Box::new(owner),
            description: None,
            schema_id,
            last_sync,
            merged_time: None,
            merged_by: Box::new(merged_by),
            comments: None,
            tags: None,
            custom_fields: None,
            created,
            last_updated,
        }
    }
}


