/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.2-Docker-3.4.1 (4.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// BranchEvent : Adds support for custom fields and tags.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BranchEvent {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "display")]
    pub display: String,
    #[serde(rename = "time")]
    pub time: String,
    #[serde(rename = "branch")]
    pub branch: Box<crate::models::BriefBranch>,
    #[serde(rename = "user")]
    pub user: Box<crate::models::BriefUser>,
    #[serde(rename = "type")]
    pub r#type: Box<crate::models::BranchEventType>,
}

impl BranchEvent {
    /// Adds support for custom fields and tags.
    pub fn new(
        id: i32,
        url: String,
        display: String,
        time: String,
        branch: crate::models::BriefBranch,
        user: crate::models::BriefUser,
        r#type: crate::models::BranchEventType,
    ) -> BranchEvent {
        BranchEvent {
            id,
            url,
            display,
            time,
            branch: Box::new(branch),
            user: Box::new(user),
            r#type: Box::new(r#type),
        }
    }
}
