/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.2-Docker-3.4.1 (4.4)
 * 
 * Generated by: https://openapi-generator.tech
 */

/// BriefDataFile : Adds support for custom fields and tags.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BriefDataFile {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "display")]
    pub display: String,
    /// File path relative to the data source's root
    #[serde(rename = "path")]
    pub path: String,
}

impl BriefDataFile {
    /// Adds support for custom fields and tags.
    pub fn new(id: i32, url: String, display: String, path: String) -> BriefDataFile {
        BriefDataFile {
            id,
            url,
            display,
            path,
        }
    }
}


