/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.3 (4.6)
 *
 * Generated by: https://openapi-generator.tech
 */

/// BriefDeviceTypeRequest : Base serializer class for models inheriting from PrimaryModel.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BriefDeviceTypeRequest {
    #[serde(rename = "manufacturer")]
    pub manufacturer: Box<crate::models::BriefDeviceTypeRequestManufacturer>,
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl BriefDeviceTypeRequest {
    /// Base serializer class for models inheriting from PrimaryModel.
    pub fn new(
        manufacturer: crate::models::BriefDeviceTypeRequestManufacturer,
        model: String,
        slug: String,
    ) -> BriefDeviceTypeRequest {
        BriefDeviceTypeRequest {
            manufacturer: Box::new(manufacturer),
            model,
            slug,
            description: None,
        }
    }
}
