/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.2-Docker-3.4.1 (4.4)
 * 
 * Generated by: https://openapi-generator.tech
 */

/// BriefRackTypeRequest : Adds support for custom fields and tags.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BriefRackTypeRequest {
    #[serde(rename = "manufacturer")]
    pub manufacturer: Box<crate::models::BriefDeviceTypeRequestManufacturer>,
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl BriefRackTypeRequest {
    /// Adds support for custom fields and tags.
    pub fn new(manufacturer: crate::models::BriefDeviceTypeRequestManufacturer, model: String, slug: String) -> BriefRackTypeRequest {
        BriefRackTypeRequest {
            manufacturer: Box::new(manufacturer),
            model,
            slug,
            description: None,
        }
    }
}


