/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.5.9-Docker-4.0.2 (4.5)
 *
 * Generated by: https://openapi-generator.tech
 */

/// BriefCustomFieldChoiceSetRequest : Adds an `owner` field for models which have a ForeignKey to users.Owner.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BriefCustomFieldChoiceSetRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl BriefCustomFieldChoiceSetRequest {
    /// Adds an `owner` field for models which have a ForeignKey to users.Owner.
    pub fn new(name: String) -> BriefCustomFieldChoiceSetRequest {
        BriefCustomFieldChoiceSetRequest {
            name,
            description: None,
        }
    }
}
