/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.2-Docker-3.4.1 (4.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// BriefCircuitGroupAssignmentSerializer : Base serializer for group assignments under CircuitSerializer.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BriefCircuitGroupAssignmentSerializer {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    #[serde(rename = "group")]
    pub group: Box<crate::models::BriefCircuitGroup>,
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<Box<crate::models::BriefCircuitGroupAssignmentSerializerPriority>>,
}

impl BriefCircuitGroupAssignmentSerializer {
    /// Base serializer for group assignments under CircuitSerializer.
    pub fn new(group: crate::models::BriefCircuitGroup) -> BriefCircuitGroupAssignmentSerializer {
        BriefCircuitGroupAssignmentSerializer {
            id: None,
            url: None,
            display: None,
            group: Box::new(group),
            priority: None,
        }
    }
}
