/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.2 (4.6)
 *
 * Generated by: https://openapi-generator.tech
 */

/// BriefVirtualChassisRequest : Base serializer class for models inheriting from PrimaryModel.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BriefVirtualChassisRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(
        rename = "master",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub master: Option<Option<Box<crate::models::NestedDeviceRequest>>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl BriefVirtualChassisRequest {
    /// Base serializer class for models inheriting from PrimaryModel.
    pub fn new(name: String) -> BriefVirtualChassisRequest {
        BriefVirtualChassisRequest {
            name,
            master: None,
            description: None,
        }
    }
}
