/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.2-Docker-3.4.1 (4.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// BriefCircuit : Adds support for custom fields and tags.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BriefCircuit {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "display")]
    pub display: String,
    /// Unique circuit ID
    #[serde(rename = "cid")]
    pub cid: String,
    #[serde(rename = "provider")]
    pub provider: Box<crate::models::BriefProvider>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl BriefCircuit {
    /// Adds support for custom fields and tags.
    pub fn new(
        id: i32,
        url: String,
        display: String,
        cid: String,
        provider: crate::models::BriefProvider,
    ) -> BriefCircuit {
        BriefCircuit {
            id,
            url,
            display,
            cid,
            provider: Box::new(provider),
            description: None,
        }
    }
}
