/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.3 (4.6)
 *
 * Generated by: https://openapi-generator.tech
 */

/// BriefCircuit : Base serializer class for models inheriting from PrimaryModel.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BriefCircuit {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    /// Unique circuit ID
    #[serde(rename = "cid")]
    pub cid: String,
    #[serde(rename = "provider")]
    pub provider: Box<crate::models::BriefProvider>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl BriefCircuit {
    /// Base serializer class for models inheriting from PrimaryModel.
    pub fn new(cid: String, provider: crate::models::BriefProvider) -> BriefCircuit {
        BriefCircuit {
            id: None,
            url: None,
            display: None,
            cid,
            provider: Box::new(provider),
            description: None,
        }
    }
}
