/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.5.9-Docker-4.0.2 (4.5)
 *
 * Generated by: https://openapi-generator.tech
 */

/// BriefModuleTypeRequest : Base serializer class for models inheriting from PrimaryModel.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BriefModuleTypeRequest {
    #[serde(
        rename = "profile",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub profile: Option<Option<Box<crate::models::BriefModuleTypeRequestProfile>>>,
    #[serde(rename = "manufacturer")]
    pub manufacturer: Box<crate::models::BriefDeviceTypeRequestManufacturer>,
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl BriefModuleTypeRequest {
    /// Base serializer class for models inheriting from PrimaryModel.
    pub fn new(
        manufacturer: crate::models::BriefDeviceTypeRequestManufacturer,
        model: String,
    ) -> BriefModuleTypeRequest {
        BriefModuleTypeRequest {
            profile: None,
            manufacturer: Box::new(manufacturer),
            model,
            description: None,
        }
    }
}
