/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.2-Docker-3.4.1 (4.4)
 * 
 * Generated by: https://openapi-generator.tech
 */

/// BriefPlatform : Extends PrimaryModelSerializer to include MPTT support.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BriefPlatform {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "display")]
    pub display: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "device_count")]
    pub device_count: i32,
    #[serde(rename = "virtualmachine_count")]
    pub virtualmachine_count: i32,
    #[serde(rename = "_depth")]
    pub _depth: i32,
}

impl BriefPlatform {
    /// Extends PrimaryModelSerializer to include MPTT support.
    pub fn new(id: i32, url: String, display: String, name: String, slug: String, device_count: i32, virtualmachine_count: i32, _depth: i32) -> BriefPlatform {
        BriefPlatform {
            id,
            url,
            display,
            name,
            slug,
            description: None,
            device_count,
            virtualmachine_count,
            _depth,
        }
    }
}


