/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.5.9-Docker-4.0.2 (4.5)
 *
 * Generated by: https://openapi-generator.tech
 */

/// BriefInventoryItemRoleRequest : Base serializer class for models inheriting from OrganizationalModel.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BriefInventoryItemRoleRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl BriefInventoryItemRoleRequest {
    /// Base serializer class for models inheriting from OrganizationalModel.
    pub fn new(name: String, slug: String) -> BriefInventoryItemRoleRequest {
        BriefInventoryItemRoleRequest {
            name,
            slug,
            description: None,
        }
    }
}
