/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.3 (4.6)
 *
 * Generated by: https://openapi-generator.tech
 */

/// BriefDeviceRole : Base serializer class for models inheriting from NestedGroupModel.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BriefDeviceRole {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "device_count", skip_serializing_if = "Option::is_none")]
    pub device_count: Option<i32>,
    #[serde(
        rename = "virtualmachine_count",
        skip_serializing_if = "Option::is_none"
    )]
    pub virtualmachine_count: Option<i32>,
    #[serde(rename = "_depth", skip_serializing_if = "Option::is_none")]
    pub _depth: Option<i32>,
}

impl BriefDeviceRole {
    /// Base serializer class for models inheriting from NestedGroupModel.
    pub fn new(name: String, slug: String) -> BriefDeviceRole {
        BriefDeviceRole {
            id: None,
            url: None,
            display: None,
            name,
            slug,
            description: None,
            device_count: None,
            virtualmachine_count: None,
            _depth: None,
        }
    }
}
