/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.2-Docker-3.4.1 (4.4)
 * 
 * Generated by: https://openapi-generator.tech
 */

/// BriefRackType : Adds support for custom fields and tags.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BriefRackType {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "display")]
    pub display: String,
    #[serde(rename = "manufacturer")]
    pub manufacturer: Box<crate::models::BriefManufacturer>,
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl BriefRackType {
    /// Adds support for custom fields and tags.
    pub fn new(id: i32, url: String, display: String, manufacturer: crate::models::BriefManufacturer, model: String, slug: String) -> BriefRackType {
        BriefRackType {
            id,
            url,
            display,
            manufacturer: Box::new(manufacturer),
            model,
            slug,
            description: None,
        }
    }
}


