/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.7.1-Docker-5.1.1 (4.7)
 *
 * Generated by: https://openapi-generator.tech
 */

/// BriefAsn : Base serializer class for models inheriting from PrimaryModel.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BriefAsn {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    /// 16- or 32-bit autonomous system number
    #[serde(rename = "asn")]
    pub asn: i64,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl BriefAsn {
    /// Base serializer class for models inheriting from PrimaryModel.
    pub fn new(asn: i64) -> BriefAsn {
        BriefAsn {
            id: None,
            url: None,
            display: None,
            asn,
            description: None,
        }
    }
}
