/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.8 (4.6)
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BulkWirelessLanRequestGroup {}

impl BulkWirelessLanRequestGroup {
    pub fn new() -> BulkWirelessLanRequestGroup {
        BulkWirelessLanRequestGroup {}
    }
}
