/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.8 (4.6)
 *
 * Generated by: https://openapi-generator.tech
 */

/// BulkMacAddressRequest : Base serializer class for models inheriting from PrimaryModel.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BulkMacAddressRequest {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "mac_address")]
    pub mac_address: String,
    #[serde(
        rename = "assigned_object_type",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub assigned_object_type: Option<Option<String>>,
    #[serde(
        rename = "assigned_object_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub assigned_object_id: Option<Option<i64>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(
        rename = "owner",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub owner: Option<Option<Box<crate::models::AsnRangeRequestOwner>>>,
    #[serde(rename = "comments", skip_serializing_if = "Option::is_none")]
    pub comments: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::NestedTagRequest>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl BulkMacAddressRequest {
    /// Base serializer class for models inheriting from PrimaryModel.
    pub fn new(id: i32, mac_address: String) -> BulkMacAddressRequest {
        BulkMacAddressRequest {
            id,
            mac_address,
            assigned_object_type: None,
            assigned_object_id: None,
            description: None,
            owner: None,
            comments: None,
            tags: None,
            custom_fields: None,
        }
    }
}
