/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.7.0-Docker-5.1.1 (4.7)
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BulkCoolingSourceRequestSite {
    /// Full name of the site
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl BulkCoolingSourceRequestSite {
    pub fn new(name: String, slug: String) -> BulkCoolingSourceRequestSite {
        BulkCoolingSourceRequestSite {
            name,
            slug,
            description: None,
        }
    }
}
