/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.8 (4.6)
 *
 * Generated by: https://openapi-generator.tech
 */

/// BulkL2VpnTerminationRequest : Adds support for custom fields and tags.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BulkL2VpnTerminationRequest {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "l2vpn")]
    pub l2vpn: Box<crate::models::BriefL2VpnTerminationRequestL2vpn>,
    #[serde(rename = "assigned_object_type")]
    pub assigned_object_type: String,
    #[serde(rename = "assigned_object_id")]
    pub assigned_object_id: i64,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::NestedTagRequest>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl BulkL2VpnTerminationRequest {
    /// Adds support for custom fields and tags.
    pub fn new(
        id: i32,
        l2vpn: crate::models::BriefL2VpnTerminationRequestL2vpn,
        assigned_object_type: String,
        assigned_object_id: i64,
    ) -> BulkL2VpnTerminationRequest {
        BulkL2VpnTerminationRequest {
            id,
            l2vpn: Box::new(l2vpn),
            assigned_object_type,
            assigned_object_id,
            tags: None,
            custom_fields: None,
        }
    }
}
