/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.2-Docker-3.4.1 (4.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// ChangeDiff : Adds support for custom fields and tags.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ChangeDiff {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "display")]
    pub display: String,
    #[serde(rename = "branch")]
    pub branch: Box<crate::models::BriefBranch>,
    #[serde(rename = "object_type")]
    pub object_type: String,
    #[serde(rename = "object_id")]
    pub object_id: i64,
    #[serde(rename = "object", deserialize_with = "Option::deserialize")]
    pub object: Option<serde_json::Value>,
    #[serde(rename = "object_repr")]
    pub object_repr: String,
    #[serde(rename = "action")]
    pub action: Box<crate::models::ChangeDiffAction>,
    #[serde(rename = "conflicts", deserialize_with = "Option::deserialize")]
    pub conflicts: Option<Vec<String>>,
    #[serde(rename = "diff", deserialize_with = "Option::deserialize")]
    pub diff: Option<serde_json::Value>,
    #[serde(rename = "original_data", deserialize_with = "Option::deserialize")]
    pub original_data: Option<serde_json::Value>,
    #[serde(rename = "modified_data", deserialize_with = "Option::deserialize")]
    pub modified_data: Option<serde_json::Value>,
    #[serde(rename = "current_data", deserialize_with = "Option::deserialize")]
    pub current_data: Option<serde_json::Value>,
    #[serde(rename = "last_updated")]
    pub last_updated: String,
}

impl ChangeDiff {
    /// Adds support for custom fields and tags.
    pub fn new(
        id: i32,
        url: String,
        display: String,
        branch: crate::models::BriefBranch,
        object_type: String,
        object_id: i64,
        object: Option<serde_json::Value>,
        object_repr: String,
        action: crate::models::ChangeDiffAction,
        conflicts: Option<Vec<String>>,
        diff: Option<serde_json::Value>,
        original_data: Option<serde_json::Value>,
        modified_data: Option<serde_json::Value>,
        current_data: Option<serde_json::Value>,
        last_updated: String,
    ) -> ChangeDiff {
        ChangeDiff {
            id,
            url,
            display,
            branch: Box::new(branch),
            object_type,
            object_id,
            object,
            object_repr,
            action: Box::new(action),
            conflicts,
            diff,
            original_data,
            modified_data,
            current_data,
            last_updated,
        }
    }
}
