/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.2-Docker-3.4.1 (4.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// CircuitCircuitTerminationRequest : Represents an object related through a ForeignKey field. On write, it accepts a primary key (PK) value or a dictionary of attributes which can be used to uniquely identify the related object. This class should be subclassed to return a full representation of the related object on read.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CircuitCircuitTerminationRequest {
    #[serde(
        rename = "termination_type",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub termination_type: Option<Option<String>>,
    #[serde(
        rename = "termination_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub termination_id: Option<Option<i32>>,
    /// Physical circuit speed
    #[serde(
        rename = "port_speed",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub port_speed: Option<Option<i32>>,
    /// Upstream speed, if different from port speed
    #[serde(
        rename = "upstream_speed",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub upstream_speed: Option<Option<i32>>,
    /// ID of the local cross-connect
    #[serde(rename = "xconnect_id", skip_serializing_if = "Option::is_none")]
    pub xconnect_id: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl CircuitCircuitTerminationRequest {
    /// Represents an object related through a ForeignKey field. On write, it accepts a primary key (PK) value or a dictionary of attributes which can be used to uniquely identify the related object. This class should be subclassed to return a full representation of the related object on read.
    pub fn new() -> CircuitCircuitTerminationRequest {
        CircuitCircuitTerminationRequest {
            termination_type: None,
            termination_id: None,
            port_speed: None,
            upstream_speed: None,
            xconnect_id: None,
            description: None,
        }
    }
}
