/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.2-Docker-3.4.1 (4.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// CircuitGroupAssignment : Base serializer for group assignments under CircuitSerializer.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CircuitGroupAssignment {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "display_url", skip_serializing_if = "Option::is_none")]
    pub display_url: Option<String>,
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    #[serde(rename = "group")]
    pub group: Box<crate::models::BriefCircuitGroup>,
    #[serde(rename = "member_type")]
    pub member_type: String,
    #[serde(rename = "member_id")]
    pub member_id: i64,
    #[serde(
        rename = "member",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub member: Option<Option<serde_json::Value>>,
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<Box<crate::models::BriefCircuitGroupAssignmentSerializerPriority>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::NestedTag>>,
    #[serde(
        rename = "created",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub created: Option<Option<String>>,
    #[serde(
        rename = "last_updated",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_updated: Option<Option<String>>,
}

impl CircuitGroupAssignment {
    /// Base serializer for group assignments under CircuitSerializer.
    pub fn new(
        group: crate::models::BriefCircuitGroup,
        member_type: String,
        member_id: i64,
    ) -> CircuitGroupAssignment {
        CircuitGroupAssignment {
            id: None,
            url: None,
            display_url: None,
            display: None,
            group: Box::new(group),
            member_type,
            member_id,
            member: None,
            priority: None,
            tags: None,
            created: None,
            last_updated: None,
        }
    }
}
