/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.2-Docker-3.4.1 (4.4)
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CircuitGroupAssignmentRequest : Base serializer for group assignments under CircuitSerializer.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CircuitGroupAssignmentRequest {
    #[serde(rename = "group")]
    pub group: Box<crate::models::BriefCircuitGroupAssignmentSerializerRequestGroup>,
    #[serde(rename = "member_type")]
    pub member_type: String,
    #[serde(rename = "member_id")]
    pub member_id: i64,
    /// * `primary` - Primary * `secondary` - Secondary * `tertiary` - Tertiary * `inactive` - Inactive
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<Priority>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::NestedTagRequest>>,
}

impl CircuitGroupAssignmentRequest {
    /// Base serializer for group assignments under CircuitSerializer.
    pub fn new(group: crate::models::BriefCircuitGroupAssignmentSerializerRequestGroup, member_type: String, member_id: i64) -> CircuitGroupAssignmentRequest {
        CircuitGroupAssignmentRequest {
            group: Box::new(group),
            member_type,
            member_id,
            priority: None,
            tags: None,
        }
    }
}

/// * `primary` - Primary * `secondary` - Secondary * `tertiary` - Tertiary * `inactive` - Inactive
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Priority {
    #[serde(rename = "primary")]
    Primary,
    #[serde(rename = "secondary")]
    Secondary,
    #[serde(rename = "tertiary")]
    Tertiary,
    #[serde(rename = "inactive")]
    Inactive,
    #[serde(rename = "")]
    Empty,
}

impl Default for Priority {
    fn default() -> Priority {
        Self::Primary
    }
}

