/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.2-Docker-3.4.1 (4.4)
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ConfigTemplateRequest : Introduces support for Tag assignment. Adds `tags` serialization, and handles tag assignment on create() and update().



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConfigTemplateRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Any <a href=\"https://jinja.palletsprojects.com/en/stable/api/#jinja2.Environment\">additional parameters</a> to pass when constructing the Jinja environment
    #[serde(rename = "environment_params", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub environment_params: Option<Option<serde_json::Value>>,
    /// Jinja template code.
    #[serde(rename = "template_code")]
    pub template_code: String,
    /// Defaults to <code>text/plain; charset=utf-8</code>
    #[serde(rename = "mime_type", skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<String>,
    /// Filename to give to the rendered export file
    #[serde(rename = "file_name", skip_serializing_if = "Option::is_none")]
    pub file_name: Option<String>,
    /// Extension to append to the rendered filename
    #[serde(rename = "file_extension", skip_serializing_if = "Option::is_none")]
    pub file_extension: Option<String>,
    /// Download file as attachment
    #[serde(rename = "as_attachment", skip_serializing_if = "Option::is_none")]
    pub as_attachment: Option<bool>,
    #[serde(rename = "data_source", skip_serializing_if = "Option::is_none")]
    pub data_source: Option<Box<crate::models::ConfigContextProfileRequestDataSource>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::NestedTagRequest>>,
}

impl ConfigTemplateRequest {
    /// Introduces support for Tag assignment. Adds `tags` serialization, and handles tag assignment on create() and update().
    pub fn new(name: String, template_code: String) -> ConfigTemplateRequest {
        ConfigTemplateRequest {
            name,
            description: None,
            environment_params: None,
            template_code,
            mime_type: None,
            file_name: None,
            file_extension: None,
            as_attachment: None,
            data_source: None,
            tags: None,
        }
    }
}


