/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.2-Docker-3.4.1 (4.4)
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ConfigTemplate : Introduces support for Tag assignment. Adds `tags` serialization, and handles tag assignment on create() and update().



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConfigTemplate {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "display_url")]
    pub display_url: String,
    #[serde(rename = "display")]
    pub display: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Any <a href=\"https://jinja.palletsprojects.com/en/stable/api/#jinja2.Environment\">additional parameters</a> to pass when constructing the Jinja environment
    #[serde(rename = "environment_params", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub environment_params: Option<Option<serde_json::Value>>,
    /// Jinja template code.
    #[serde(rename = "template_code")]
    pub template_code: String,
    /// Defaults to <code>text/plain; charset=utf-8</code>
    #[serde(rename = "mime_type", skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<String>,
    /// Filename to give to the rendered export file
    #[serde(rename = "file_name", skip_serializing_if = "Option::is_none")]
    pub file_name: Option<String>,
    /// Extension to append to the rendered filename
    #[serde(rename = "file_extension", skip_serializing_if = "Option::is_none")]
    pub file_extension: Option<String>,
    /// Download file as attachment
    #[serde(rename = "as_attachment", skip_serializing_if = "Option::is_none")]
    pub as_attachment: Option<bool>,
    #[serde(rename = "data_source", skip_serializing_if = "Option::is_none")]
    pub data_source: Option<Box<crate::models::BriefDataSource>>,
    /// Path to remote file (relative to data source root)
    #[serde(rename = "data_path")]
    pub data_path: String,
    #[serde(rename = "data_file", skip_serializing_if = "Option::is_none")]
    pub data_file: Option<Box<crate::models::BriefDataFile>>,
    #[serde(rename = "data_synced", deserialize_with = "Option::deserialize")]
    pub data_synced: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::NestedTag>>,
    #[serde(rename = "created", deserialize_with = "Option::deserialize")]
    pub created: Option<String>,
    #[serde(rename = "last_updated", deserialize_with = "Option::deserialize")]
    pub last_updated: Option<String>,
}

impl ConfigTemplate {
    /// Introduces support for Tag assignment. Adds `tags` serialization, and handles tag assignment on create() and update().
    pub fn new(id: i32, url: String, display_url: String, display: String, name: String, template_code: String, data_path: String, data_synced: Option<String>, created: Option<String>, last_updated: Option<String>) -> ConfigTemplate {
        ConfigTemplate {
            id,
            url,
            display_url,
            display,
            name,
            description: None,
            environment_params: None,
            template_code,
            mime_type: None,
            file_name: None,
            file_extension: None,
            as_attachment: None,
            data_source: None,
            data_path,
            data_file: None,
            data_synced,
            tags: None,
            created,
            last_updated,
        }
    }
}


