/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.7.1-Docker-5.1.1 (4.7)
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CoolingIntakeType {
    /// * `uqd` - UQD (Universal Quick Disconnect) * `uqdb` - UQDB (Universal Quick Disconnect, Blind-mate) * `qdc` - QDC (Quick Disconnect Coupling) * `camlock` - Camlock (cam-and-groove) * `npt` - NPT (threaded) * `bsp` - BSP (threaded) * `proprietary` - Proprietary
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<Value>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<Label>,
}

impl CoolingIntakeType {
    pub fn new() -> CoolingIntakeType {
        CoolingIntakeType {
            value: None,
            label: None,
        }
    }
}

/// * `uqd` - UQD (Universal Quick Disconnect) * `uqdb` - UQDB (Universal Quick Disconnect, Blind-mate) * `qdc` - QDC (Quick Disconnect Coupling) * `camlock` - Camlock (cam-and-groove) * `npt` - NPT (threaded) * `bsp` - BSP (threaded) * `proprietary` - Proprietary
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Value {
    #[serde(rename = "uqd")]
    Uqd,
    #[serde(rename = "uqdb")]
    Uqdb,
    #[serde(rename = "qdc")]
    Qdc,
    #[serde(rename = "camlock")]
    Camlock,
    #[serde(rename = "npt")]
    Npt,
    #[serde(rename = "bsp")]
    Bsp,
    #[serde(rename = "proprietary")]
    Proprietary,
    #[serde(rename = "")]
    Empty,
    #[serde(rename = "null")]
    Null,
}

impl Default for Value {
    fn default() -> Value {
        Self::Uqd
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Label {
    #[serde(rename = "UQD (Universal Quick Disconnect)")]
    UqdLeftParenthesisUniversalQuickDisconnectRightParenthesis,
    #[serde(rename = "UQDB (Universal Quick Disconnect, Blind-mate)")]
    UqdbLeftParenthesisUniversalQuickDisconnectCommaBlindMateRightParenthesis,
    #[serde(rename = "QDC (Quick Disconnect Coupling)")]
    QdcLeftParenthesisQuickDisconnectCouplingRightParenthesis,
    #[serde(rename = "Camlock (cam-and-groove)")]
    CamlockLeftParenthesisCamAndGrooveRightParenthesis,
    #[serde(rename = "NPT (threaded)")]
    NptLeftParenthesisThreadedRightParenthesis,
    #[serde(rename = "BSP (threaded)")]
    BspLeftParenthesisThreadedRightParenthesis,
    #[serde(rename = "Proprietary")]
    Proprietary,
}

impl Default for Label {
    fn default() -> Label {
        Self::UqdLeftParenthesisUniversalQuickDisconnectRightParenthesis
    }
}
