/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.7.0-Docker-5.1.1 (4.7)
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DcimCoolingSourcesCreateRequest {
    #[serde(rename = "site")]
    pub site: Box<crate::models::BulkCoolingSourceRequestSite>,
    #[serde(
        rename = "location",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub location: Option<Option<Box<crate::models::BulkCoolingSourceRequestLocation>>>,
    #[serde(rename = "name")]
    pub name: String,
    /// * `chiller` - Chiller * `cooling-tower` - Cooling tower * `dry-cooler` - Dry cooler * `crac` - CRAC * `crah` - CRAH
    #[serde(rename = "type")]
    pub r#type: RHashType,
    /// * `offline` - Offline * `active` - Active * `planned` - Planned * `failed` - Failed
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// * `water` - Water * `water-glycol` - Water/glycol * `dielectric` - Dielectric * `refrigerant` - Refrigerant
    #[serde(
        rename = "fluid_type",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub fluid_type: Option<Option<FluidType>>,
    /// Total rated cooling capacity (kW)
    #[serde(
        rename = "cooling_capacity",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub cooling_capacity: Option<Option<f64>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(
        rename = "owner",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub owner: Option<Option<Box<crate::models::AsnRangeRequestOwner>>>,
    #[serde(rename = "comments", skip_serializing_if = "Option::is_none")]
    pub comments: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::NestedTagRequest>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl DcimCoolingSourcesCreateRequest {
    pub fn new(
        site: crate::models::BulkCoolingSourceRequestSite,
        name: String,
        r#type: RHashType,
    ) -> DcimCoolingSourcesCreateRequest {
        DcimCoolingSourcesCreateRequest {
            site: Box::new(site),
            location: None,
            name,
            r#type,
            status: None,
            fluid_type: None,
            cooling_capacity: None,
            description: None,
            owner: None,
            comments: None,
            tags: None,
            custom_fields: None,
        }
    }
}

/// * `chiller` - Chiller * `cooling-tower` - Cooling tower * `dry-cooler` - Dry cooler * `crac` - CRAC * `crah` - CRAH
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "chiller")]
    Chiller,
    #[serde(rename = "cooling-tower")]
    CoolingTower,
    #[serde(rename = "dry-cooler")]
    DryCooler,
    #[serde(rename = "crac")]
    Crac,
    #[serde(rename = "crah")]
    Crah,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Chiller
    }
}
/// * `offline` - Offline * `active` - Active * `planned` - Planned * `failed` - Failed
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "offline")]
    Offline,
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "planned")]
    Planned,
    #[serde(rename = "failed")]
    Failed,
}

impl Default for Status {
    fn default() -> Status {
        Self::Offline
    }
}
/// * `water` - Water * `water-glycol` - Water/glycol * `dielectric` - Dielectric * `refrigerant` - Refrigerant
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FluidType {
    #[serde(rename = "water")]
    Water,
    #[serde(rename = "water-glycol")]
    WaterGlycol,
    #[serde(rename = "dielectric")]
    Dielectric,
    #[serde(rename = "refrigerant")]
    Refrigerant,
    #[serde(rename = "")]
    Empty,
    #[serde(rename = "null")]
    Null,
}

impl Default for FluidType {
    fn default() -> FluidType {
        Self::Water
    }
}
