/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.3 (4.6)
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DcimInventoryItemTemplatesCreateRequest {
    #[serde(rename = "device_type")]
    pub device_type: Box<crate::models::BulkDeviceBayTemplateRequestDeviceType>,
    #[serde(
        rename = "parent",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub parent: Option<Option<i32>>,
    /// {module} is accepted as a substitution for the module bay position when attached to a module type.
    #[serde(rename = "name")]
    pub name: String,
    /// Physical label
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(
        rename = "role",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub role: Option<Option<Box<crate::models::BulkInventoryItemRequestRole>>>,
    #[serde(
        rename = "manufacturer",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub manufacturer: Option<Option<Box<crate::models::BulkInventoryItemRequestManufacturer>>>,
    /// Manufacturer-assigned part identifier
    #[serde(rename = "part_id", skip_serializing_if = "Option::is_none")]
    pub part_id: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(
        rename = "component_type",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub component_type: Option<Option<String>>,
    #[serde(
        rename = "component_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub component_id: Option<Option<i64>>,
}

impl DcimInventoryItemTemplatesCreateRequest {
    pub fn new(
        device_type: crate::models::BulkDeviceBayTemplateRequestDeviceType,
        name: String,
    ) -> DcimInventoryItemTemplatesCreateRequest {
        DcimInventoryItemTemplatesCreateRequest {
            device_type: Box::new(device_type),
            parent: None,
            name,
            label: None,
            role: None,
            manufacturer: None,
            part_id: None,
            description: None,
            component_type: None,
            component_id: None,
        }
    }
}
