/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.5.9-Docker-4.0.2 (4.5)
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ExtrasCustomFieldChoiceSetsCreateRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Base set of predefined choices (optional)  * `IATA` - IATA (Airport codes) * `ISO_3166` - ISO 3166 (Country codes) * `UN_LOCODE` - UN/LOCODE (Location codes)
    #[serde(
        rename = "base_choices",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub base_choices: Option<Option<BaseChoices>>,
    #[serde(rename = "extra_choices")]
    pub extra_choices: Vec<Vec<serde_json::Value>>,
    /// Choices are automatically ordered alphabetically
    #[serde(
        rename = "order_alphabetically",
        skip_serializing_if = "Option::is_none"
    )]
    pub order_alphabetically: Option<bool>,
    #[serde(
        rename = "owner",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub owner: Option<Option<Box<crate::models::AsnRangeRequestOwner>>>,
}

impl ExtrasCustomFieldChoiceSetsCreateRequest {
    pub fn new(
        name: String,
        extra_choices: Vec<Vec<serde_json::Value>>,
    ) -> ExtrasCustomFieldChoiceSetsCreateRequest {
        ExtrasCustomFieldChoiceSetsCreateRequest {
            name,
            description: None,
            base_choices: None,
            extra_choices,
            order_alphabetically: None,
            owner: None,
        }
    }
}

/// Base set of predefined choices (optional)  * `IATA` - IATA (Airport codes) * `ISO_3166` - ISO 3166 (Country codes) * `UN_LOCODE` - UN/LOCODE (Location codes)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BaseChoices {
    #[serde(rename = "IATA")]
    Iata,
    #[serde(rename = "ISO_3166")]
    Iso3166,
    #[serde(rename = "UN_LOCODE")]
    UnLocode,
    #[serde(rename = "")]
    Empty,
    #[serde(rename = "null")]
    Null,
}

impl Default for BaseChoices {
    fn default() -> BaseChoices {
        Self::Iata
    }
}
