/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.3 (4.6)
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ExtrasBookmarksCreateRequest {
    #[serde(rename = "object_type")]
    pub object_type: String,
    #[serde(rename = "object_id")]
    pub object_id: i64,
    #[serde(rename = "user")]
    pub user: Box<crate::models::BookmarkRequestUser>,
}

impl ExtrasBookmarksCreateRequest {
    pub fn new(
        object_type: String,
        object_id: i64,
        user: crate::models::BookmarkRequestUser,
    ) -> ExtrasBookmarksCreateRequest {
        ExtrasBookmarksCreateRequest {
            object_type,
            object_id,
            user: Box::new(user),
        }
    }
}
