/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.2 (4.6)
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FrontPortMappingRequest {
    #[serde(rename = "position")]
    pub position: i32,
    #[serde(rename = "rear_port")]
    pub rear_port: i32,
    #[serde(rename = "rear_port_position", skip_serializing_if = "Option::is_none")]
    pub rear_port_position: Option<i32>,
}

impl FrontPortMappingRequest {
    pub fn new(position: i32, rear_port: i32) -> FrontPortMappingRequest {
        FrontPortMappingRequest {
            position,
            rear_port,
            rear_port_position: None,
        }
    }
}
