/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.2-Docker-3.4.1 (4.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// IkeProposal : Adds support for custom fields and tags.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IkeProposal {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "display_url")]
    pub display_url: String,
    #[serde(rename = "display")]
    pub display: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "authentication_method")]
    pub authentication_method: Box<crate::models::IkeProposalAuthenticationMethod>,
    #[serde(rename = "encryption_algorithm")]
    pub encryption_algorithm: Box<crate::models::IkeProposalEncryptionAlgorithm>,
    #[serde(
        rename = "authentication_algorithm",
        skip_serializing_if = "Option::is_none"
    )]
    pub authentication_algorithm: Option<Box<crate::models::IkeProposalAuthenticationAlgorithm>>,
    #[serde(rename = "group")]
    pub group: Box<crate::models::IkeProposalGroup>,
    /// Security association lifetime (in seconds)
    #[serde(
        rename = "sa_lifetime",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sa_lifetime: Option<Option<i32>>,
    #[serde(rename = "comments", skip_serializing_if = "Option::is_none")]
    pub comments: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::NestedTag>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "created", deserialize_with = "Option::deserialize")]
    pub created: Option<String>,
    #[serde(rename = "last_updated", deserialize_with = "Option::deserialize")]
    pub last_updated: Option<String>,
}

impl IkeProposal {
    /// Adds support for custom fields and tags.
    pub fn new(
        id: i32,
        url: String,
        display_url: String,
        display: String,
        name: String,
        authentication_method: crate::models::IkeProposalAuthenticationMethod,
        encryption_algorithm: crate::models::IkeProposalEncryptionAlgorithm,
        group: crate::models::IkeProposalGroup,
        created: Option<String>,
        last_updated: Option<String>,
    ) -> IkeProposal {
        IkeProposal {
            id,
            url,
            display_url,
            display,
            name,
            description: None,
            authentication_method: Box::new(authentication_method),
            encryption_algorithm: Box::new(encryption_algorithm),
            authentication_algorithm: None,
            group: Box::new(group),
            sa_lifetime: None,
            comments: None,
            tags: None,
            custom_fields: None,
            created,
            last_updated,
        }
    }
}
