/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.2-Docker-3.4.1 (4.4)
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IpSecProfileMode {
    /// * `esp` - ESP * `ah` - AH
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<Value>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<Label>,
}

impl IpSecProfileMode {
    pub fn new() -> IpSecProfileMode {
        IpSecProfileMode {
            value: None,
            label: None,
        }
    }
}

/// * `esp` - ESP * `ah` - AH
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Value {
    #[serde(rename = "esp")]
    Esp,
    #[serde(rename = "ah")]
    Ah,
}

impl Default for Value {
    fn default() -> Value {
        Self::Esp
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Label {
    #[serde(rename = "ESP")]
    Esp,
    #[serde(rename = "AH")]
    Ah,
}

impl Default for Label {
    fn default() -> Label {
        Self::Esp
    }
}

