/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.0 (4.6)
 *
 * Generated by: https://openapi-generator.tech
 */

/// ModuleBayRequest : Adds an `owner` field for models which have a ForeignKey to users.Owner.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ModuleBayRequest {
    #[serde(rename = "device")]
    pub device: Box<crate::models::BriefInterfaceRequestDevice>,
    #[serde(
        rename = "module",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub module: Option<Option<Box<crate::models::ConsolePortRequestModule>>>,
    #[serde(rename = "name")]
    pub name: String,
    /// Physical label
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// Identifier to reference when renaming installed components
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<String>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(
        rename = "installed_module",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub installed_module: Option<Option<Box<crate::models::ConsolePortRequestModule>>>,
    #[serde(
        rename = "owner",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub owner: Option<Option<Box<crate::models::AsnRangeRequestOwner>>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::NestedTagRequest>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl ModuleBayRequest {
    /// Adds an `owner` field for models which have a ForeignKey to users.Owner.
    pub fn new(
        device: crate::models::BriefInterfaceRequestDevice,
        name: String,
    ) -> ModuleBayRequest {
        ModuleBayRequest {
            device: Box::new(device),
            module: None,
            name,
            label: None,
            position: None,
            enabled: None,
            description: None,
            installed_module: None,
            owner: None,
            tags: None,
            custom_fields: None,
        }
    }
}
