/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.2-Docker-3.4.1 (4.4)
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ModuleRequestModuleType {
    #[serde(
        rename = "profile",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub profile: Option<Option<Box<crate::models::BriefModuleTypeRequestProfile>>>,
    #[serde(rename = "manufacturer")]
    pub manufacturer: Box<crate::models::BriefDeviceTypeRequestManufacturer>,
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl ModuleRequestModuleType {
    pub fn new(
        manufacturer: crate::models::BriefDeviceTypeRequestManufacturer,
        model: String,
    ) -> ModuleRequestModuleType {
        ModuleRequestModuleType {
            profile: None,
            manufacturer: Box::new(manufacturer),
            model,
            description: None,
        }
    }
}
