/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.2-Docker-3.4.1 (4.4)
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ObjectType {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    #[serde(rename = "app_label")]
    pub app_label: String,
    #[serde(rename = "app_name", skip_serializing_if = "Option::is_none")]
    pub app_name: Option<String>,
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "model_name", skip_serializing_if = "Option::is_none")]
    pub model_name: Option<String>,
    #[serde(rename = "model_name_plural", skip_serializing_if = "Option::is_none")]
    pub model_name_plural: Option<String>,
    #[serde(rename = "public", skip_serializing_if = "Option::is_none")]
    pub public: Option<bool>,
    #[serde(rename = "features", skip_serializing_if = "Option::is_none")]
    pub features: Option<Vec<String>>,
    #[serde(rename = "is_plugin_model", skip_serializing_if = "Option::is_none")]
    pub is_plugin_model: Option<bool>,
    #[serde(rename = "rest_api_endpoint", skip_serializing_if = "Option::is_none")]
    pub rest_api_endpoint: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl ObjectType {
    pub fn new(app_label: String, model: String) -> ObjectType {
        ObjectType {
            id: None,
            url: None,
            display: None,
            app_label,
            app_name: None,
            model,
            model_name: None,
            model_name_plural: None,
            public: None,
            features: None,
            is_plugin_model: None,
            rest_api_endpoint: None,
            description: None,
        }
    }
}
