/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.3 (4.6)
 *
 * Generated by: https://openapi-generator.tech
 */

/// PatchedBulkVlanTranslationPolicyRequest : Base serializer class for models inheriting from PrimaryModel.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchedBulkVlanTranslationPolicyRequest {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(
        rename = "owner",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub owner: Option<Option<Box<crate::models::AsnRangeRequestOwner>>>,
    #[serde(rename = "comments", skip_serializing_if = "Option::is_none")]
    pub comments: Option<String>,
}

impl PatchedBulkVlanTranslationPolicyRequest {
    /// Base serializer class for models inheriting from PrimaryModel.
    pub fn new(id: i32) -> PatchedBulkVlanTranslationPolicyRequest {
        PatchedBulkVlanTranslationPolicyRequest {
            id,
            name: None,
            description: None,
            owner: None,
            comments: None,
        }
    }
}
