/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.2-Docker-3.4.1 (4.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// PatchedWritableIpSecProfileRequest : Adds support for custom fields and tags.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchedWritableIpSecProfileRequest {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// * `esp` - ESP * `ah` - AH
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<Mode>,
    #[serde(rename = "ike_policy", skip_serializing_if = "Option::is_none")]
    pub ike_policy: Option<Box<crate::models::IpSecProfileRequestIkePolicy>>,
    #[serde(rename = "ipsec_policy", skip_serializing_if = "Option::is_none")]
    pub ipsec_policy: Option<Box<crate::models::IpSecProfileRequestIpsecPolicy>>,
    #[serde(rename = "comments", skip_serializing_if = "Option::is_none")]
    pub comments: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::NestedTagRequest>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl PatchedWritableIpSecProfileRequest {
    /// Adds support for custom fields and tags.
    pub fn new() -> PatchedWritableIpSecProfileRequest {
        PatchedWritableIpSecProfileRequest {
            name: None,
            description: None,
            mode: None,
            ike_policy: None,
            ipsec_policy: None,
            comments: None,
            tags: None,
            custom_fields: None,
        }
    }
}

/// * `esp` - ESP * `ah` - AH
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mode {
    #[serde(rename = "esp")]
    Esp,
    #[serde(rename = "ah")]
    Ah,
}

impl Default for Mode {
    fn default() -> Mode {
        Self::Esp
    }
}
