/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.7.0-Docker-5.1.1 (4.7)
 *
 * Generated by: https://openapi-generator.tech
 */

/// PatchedWritableServiceRequest : Shared port-mapping handling for the Service and ServiceTemplate serializers, including backward compatibility for the legacy single-protocol ``protocol``/``ports`` representation.  Read: alongside the ``port_mappings`` list, a service that uses a single protocol also reports the legacy ``protocol`` and ``ports`` fields; a multi-protocol service reports ``null`` for both (it cannot be expressed in the old single-protocol format).  Write: either format is accepted. When the legacy ``protocol``/``ports`` pair is supplied (and ``port_mappings`` is not), it is translated into ``port_mappings``. Supplying both together is accepted only when the legacy fields agree with what ``port_mappings`` implies (e.g. a full-object round-trip that echoes back the read representation); a genuine conflict is rejected as ambiguous.  Subclassing ``serializers.Serializer`` (rather than a plain mixin) lets DRF's metaclass collect the fields declared here into the inheriting serializers.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchedWritableServiceRequest {
    #[serde(rename = "parent_object_type", skip_serializing_if = "Option::is_none")]
    pub parent_object_type: Option<String>,
    #[serde(rename = "parent_object_id", skip_serializing_if = "Option::is_none")]
    pub parent_object_id: Option<i64>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "port_mappings", skip_serializing_if = "Option::is_none")]
    pub port_mappings: Option<Vec<String>>,
    /// Deprecated; use port_mappings. Reported only for single-protocol services.
    #[serde(
        rename = "protocol",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub protocol: Option<Option<Protocol>>,
    /// Deprecated; use port_mappings. Reported only for single-protocol services.
    #[serde(
        rename = "ports",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub ports: Option<Option<Vec<i32>>>,
    #[serde(rename = "ipaddresses", skip_serializing_if = "Option::is_none")]
    pub ipaddresses: Option<Vec<i32>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(
        rename = "owner",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub owner: Option<Option<Box<crate::models::AsnRangeRequestOwner>>>,
    #[serde(rename = "comments", skip_serializing_if = "Option::is_none")]
    pub comments: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::NestedTagRequest>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl PatchedWritableServiceRequest {
    /// Shared port-mapping handling for the Service and ServiceTemplate serializers, including backward compatibility for the legacy single-protocol ``protocol``/``ports`` representation.  Read: alongside the ``port_mappings`` list, a service that uses a single protocol also reports the legacy ``protocol`` and ``ports`` fields; a multi-protocol service reports ``null`` for both (it cannot be expressed in the old single-protocol format).  Write: either format is accepted. When the legacy ``protocol``/``ports`` pair is supplied (and ``port_mappings`` is not), it is translated into ``port_mappings``. Supplying both together is accepted only when the legacy fields agree with what ``port_mappings`` implies (e.g. a full-object round-trip that echoes back the read representation); a genuine conflict is rejected as ambiguous.  Subclassing ``serializers.Serializer`` (rather than a plain mixin) lets DRF's metaclass collect the fields declared here into the inheriting serializers.
    pub fn new() -> PatchedWritableServiceRequest {
        PatchedWritableServiceRequest {
            parent_object_type: None,
            parent_object_id: None,
            name: None,
            port_mappings: None,
            protocol: None,
            ports: None,
            ipaddresses: None,
            description: None,
            owner: None,
            comments: None,
            tags: None,
            custom_fields: None,
        }
    }
}

/// Deprecated; use port_mappings. Reported only for single-protocol services.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Protocol {
    #[serde(rename = "tcp")]
    Tcp,
    #[serde(rename = "udp")]
    Udp,
    #[serde(rename = "sctp")]
    Sctp,
    #[serde(rename = "null")]
    Null,
}

impl Default for Protocol {
    fn default() -> Protocol {
        Self::Tcp
    }
}
