/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.8 (4.6)
 *
 * Generated by: https://openapi-generator.tech
 */

/// PatchedBulkContactAssignmentRequest : Adds support for custom fields and tags.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchedBulkContactAssignmentRequest {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "object_type", skip_serializing_if = "Option::is_none")]
    pub object_type: Option<String>,
    #[serde(rename = "object_id", skip_serializing_if = "Option::is_none")]
    pub object_id: Option<i64>,
    #[serde(rename = "contact", skip_serializing_if = "Option::is_none")]
    pub contact: Option<Box<crate::models::BulkContactAssignmentRequestContact>>,
    #[serde(
        rename = "role",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub role: Option<Option<Box<crate::models::BulkContactAssignmentRequestRole>>>,
    /// * `primary` - Primary * `secondary` - Secondary * `tertiary` - Tertiary * `inactive` - Inactive
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<Priority>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::NestedTagRequest>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl PatchedBulkContactAssignmentRequest {
    /// Adds support for custom fields and tags.
    pub fn new(id: i32) -> PatchedBulkContactAssignmentRequest {
        PatchedBulkContactAssignmentRequest {
            id,
            object_type: None,
            object_id: None,
            contact: None,
            role: None,
            priority: None,
            tags: None,
            custom_fields: None,
        }
    }
}

/// * `primary` - Primary * `secondary` - Secondary * `tertiary` - Tertiary * `inactive` - Inactive
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Priority {
    #[serde(rename = "primary")]
    Primary,
    #[serde(rename = "secondary")]
    Secondary,
    #[serde(rename = "tertiary")]
    Tertiary,
    #[serde(rename = "inactive")]
    Inactive,
    #[serde(rename = "")]
    Empty,
}

impl Default for Priority {
    fn default() -> Priority {
        Self::Primary
    }
}
