/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.2-Docker-3.4.1 (4.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// PatchedFhrpGroupAssignmentRequest : Adds support for custom fields and tags.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchedFhrpGroupAssignmentRequest {
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<Box<crate::models::FhrpGroupAssignmentRequestGroup>>,
    #[serde(rename = "interface_type", skip_serializing_if = "Option::is_none")]
    pub interface_type: Option<String>,
    #[serde(rename = "interface_id", skip_serializing_if = "Option::is_none")]
    pub interface_id: Option<i64>,
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<i32>,
}

impl PatchedFhrpGroupAssignmentRequest {
    /// Adds support for custom fields and tags.
    pub fn new() -> PatchedFhrpGroupAssignmentRequest {
        PatchedFhrpGroupAssignmentRequest {
            group: None,
            interface_type: None,
            interface_id: None,
            priority: None,
        }
    }
}
