/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.3 (4.6)
 *
 * Generated by: https://openapi-generator.tech
 */

/// PatchedBulkVirtualDiskRequest : Adds an `owner` field for models which have a ForeignKey to users.Owner.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchedBulkVirtualDiskRequest {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "virtual_machine", skip_serializing_if = "Option::is_none")]
    pub virtual_machine: Option<Box<crate::models::BulkVmInterfaceRequestVirtualMachine>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i32>,
    #[serde(
        rename = "owner",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub owner: Option<Option<Box<crate::models::AsnRangeRequestOwner>>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::NestedTagRequest>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl PatchedBulkVirtualDiskRequest {
    /// Adds an `owner` field for models which have a ForeignKey to users.Owner.
    pub fn new(id: i32) -> PatchedBulkVirtualDiskRequest {
        PatchedBulkVirtualDiskRequest {
            id,
            virtual_machine: None,
            name: None,
            description: None,
            size: None,
            owner: None,
            tags: None,
            custom_fields: None,
        }
    }
}
