/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.2-Docker-3.4.1 (4.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// Platform : Extends PrimaryModelSerializer to include MPTT support.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Platform {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "display_url")]
    pub display_url: String,
    #[serde(rename = "display")]
    pub display: String,
    #[serde(
        rename = "parent",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub parent: Option<Option<Box<crate::models::NestedPlatform>>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(
        rename = "manufacturer",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub manufacturer: Option<Option<Box<crate::models::BriefManufacturer>>>,
    #[serde(
        rename = "config_template",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub config_template: Option<Option<Box<crate::models::BriefConfigTemplate>>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "comments", skip_serializing_if = "Option::is_none")]
    pub comments: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::NestedTag>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "created", deserialize_with = "Option::deserialize")]
    pub created: Option<String>,
    #[serde(rename = "last_updated", deserialize_with = "Option::deserialize")]
    pub last_updated: Option<String>,
    #[serde(rename = "device_count")]
    pub device_count: i32,
    #[serde(rename = "virtualmachine_count")]
    pub virtualmachine_count: i32,
    #[serde(rename = "_depth")]
    pub _depth: i32,
}

impl Platform {
    /// Extends PrimaryModelSerializer to include MPTT support.
    pub fn new(
        id: i32,
        url: String,
        display_url: String,
        display: String,
        name: String,
        slug: String,
        created: Option<String>,
        last_updated: Option<String>,
        device_count: i32,
        virtualmachine_count: i32,
        _depth: i32,
    ) -> Platform {
        Platform {
            id,
            url,
            display_url,
            display,
            parent: None,
            name,
            slug,
            manufacturer: None,
            config_template: None,
            description: None,
            comments: None,
            tags: None,
            custom_fields: None,
            created,
            last_updated,
            device_count,
            virtualmachine_count,
            _depth,
        }
    }
}
