/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.2-Docker-3.4.1 (4.4)
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PowerOutletStatus {
    /// * `enabled` - Enabled * `disabled` - Disabled * `faulty` - Faulty
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<Value>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<Label>,
}

impl PowerOutletStatus {
    pub fn new() -> PowerOutletStatus {
        PowerOutletStatus {
            value: None,
            label: None,
        }
    }
}

/// * `enabled` - Enabled * `disabled` - Disabled * `faulty` - Faulty
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Value {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
    #[serde(rename = "faulty")]
    Faulty,
}

impl Default for Value {
    fn default() -> Value {
        Self::Enabled
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Label {
    #[serde(rename = "Enabled")]
    Enabled,
    #[serde(rename = "Disabled")]
    Disabled,
    #[serde(rename = "Faulty")]
    Faulty,
}

impl Default for Label {
    fn default() -> Label {
        Self::Enabled
    }
}
