/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.2-Docker-3.4.1 (4.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// RackUnit : A rack unit is an abstraction formed by the set (rack, position, face); it does not exist as a row in the database.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RackUnit {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<f64>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "face", skip_serializing_if = "Option::is_none")]
    pub face: Option<Box<crate::models::RackUnitFace>>,
    #[serde(rename = "device", skip_serializing_if = "Option::is_none")]
    pub device: Option<Box<crate::models::BriefDevice>>,
    #[serde(rename = "occupied", skip_serializing_if = "Option::is_none")]
    pub occupied: Option<bool>,
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
}

impl RackUnit {
    /// A rack unit is an abstraction formed by the set (rack, position, face); it does not exist as a row in the database.
    pub fn new() -> RackUnit {
        RackUnit {
            id: None,
            name: None,
            face: None,
            device: None,
            occupied: None,
            display: None,
        }
    }
}
