/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.2-Docker-3.4.1 (4.4)
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Site : Adds support for custom fields and tags.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Site {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "display_url")]
    pub display_url: String,
    #[serde(rename = "display")]
    pub display: String,
    /// Full name of the site
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Box<crate::models::LocationStatus>>,
    #[serde(rename = "region", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub region: Option<Option<Box<crate::models::BriefRegion>>>,
    #[serde(rename = "group", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub group: Option<Option<Box<crate::models::BriefSiteGroup>>>,
    #[serde(rename = "tenant", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tenant: Option<Option<Box<crate::models::BriefTenant>>>,
    /// Local facility ID or description
    #[serde(rename = "facility", skip_serializing_if = "Option::is_none")]
    pub facility: Option<String>,
    #[serde(rename = "time_zone", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub time_zone: Option<Option<String>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Physical location of the building
    #[serde(rename = "physical_address", skip_serializing_if = "Option::is_none")]
    pub physical_address: Option<String>,
    /// If different from the physical address
    #[serde(rename = "shipping_address", skip_serializing_if = "Option::is_none")]
    pub shipping_address: Option<String>,
    /// GPS coordinate in decimal format (xx.yyyyyy)
    #[serde(rename = "latitude", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub latitude: Option<Option<f64>>,
    /// GPS coordinate in decimal format (xx.yyyyyy)
    #[serde(rename = "longitude", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub longitude: Option<Option<f64>>,
    #[serde(rename = "comments", skip_serializing_if = "Option::is_none")]
    pub comments: Option<String>,
    #[serde(rename = "asns", skip_serializing_if = "Option::is_none")]
    pub asns: Option<Vec<crate::models::Asn>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::NestedTag>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "created", deserialize_with = "Option::deserialize")]
    pub created: Option<String>,
    #[serde(rename = "last_updated", deserialize_with = "Option::deserialize")]
    pub last_updated: Option<String>,
    #[serde(rename = "circuit_count")]
    pub circuit_count: i64,
    #[serde(rename = "device_count")]
    pub device_count: i64,
    #[serde(rename = "prefix_count")]
    pub prefix_count: i64,
    #[serde(rename = "rack_count")]
    pub rack_count: i64,
    #[serde(rename = "virtualmachine_count")]
    pub virtualmachine_count: i64,
    #[serde(rename = "vlan_count")]
    pub vlan_count: i64,
}

impl Site {
    /// Adds support for custom fields and tags.
    pub fn new(id: i32, url: String, display_url: String, display: String, name: String, slug: String, created: Option<String>, last_updated: Option<String>, circuit_count: i64, device_count: i64, prefix_count: i64, rack_count: i64, virtualmachine_count: i64, vlan_count: i64) -> Site {
        Site {
            id,
            url,
            display_url,
            display,
            name,
            slug,
            status: None,
            region: None,
            group: None,
            tenant: None,
            facility: None,
            time_zone: None,
            description: None,
            physical_address: None,
            shipping_address: None,
            latitude: None,
            longitude: None,
            comments: None,
            asns: None,
            tags: None,
            custom_fields: None,
            created,
            last_updated,
            circuit_count,
            device_count,
            prefix_count,
            rack_count,
            virtualmachine_count,
            vlan_count,
        }
    }
}


