/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.0 (4.6)
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UsersOwnersCreateRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "group", deserialize_with = "Option::deserialize")]
    pub group: Option<Box<crate::models::OwnerRequestGroup>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "user_groups", skip_serializing_if = "Option::is_none")]
    pub user_groups: Option<Vec<i32>>,
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<Vec<i32>>,
}

impl UsersOwnersCreateRequest {
    pub fn new(
        name: String,
        group: Option<crate::models::OwnerRequestGroup>,
    ) -> UsersOwnersCreateRequest {
        UsersOwnersCreateRequest {
            name,
            group: if let Some(x) = group {
                Some(Box::new(x))
            } else {
                None
            },
            description: None,
            user_groups: None,
            users: None,
        }
    }
}
