/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.2 (4.6)
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VirtualizationVirtualDisksCreateRequest {
    #[serde(rename = "virtual_machine")]
    pub virtual_machine: Box<crate::models::PatchedVirtualDiskRequestVirtualMachine>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "size")]
    pub size: i32,
    #[serde(
        rename = "owner",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub owner: Option<Option<Box<crate::models::AsnRangeRequestOwner>>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::NestedTagRequest>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl VirtualizationVirtualDisksCreateRequest {
    pub fn new(
        virtual_machine: crate::models::PatchedVirtualDiskRequestVirtualMachine,
        name: String,
        size: i32,
    ) -> VirtualizationVirtualDisksCreateRequest {
        VirtualizationVirtualDisksCreateRequest {
            virtual_machine: Box::new(virtual_machine),
            name,
            description: None,
            size,
            owner: None,
            tags: None,
            custom_fields: None,
        }
    }
}
