/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.2-Docker-3.4.1 (4.4)
 * 
 * Generated by: https://openapi-generator.tech
 */

/// VirtualCircuitRequest : Adds support for custom fields and tags.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VirtualCircuitRequest {
    /// Unique circuit ID
    #[serde(rename = "cid")]
    pub cid: String,
    #[serde(rename = "provider_network")]
    pub provider_network: Box<crate::models::BriefVirtualCircuitRequestProviderNetwork>,
    #[serde(rename = "provider_account", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub provider_account: Option<Option<Box<crate::models::CircuitRequestProviderAccount>>>,
    #[serde(rename = "type")]
    pub r#type: Box<crate::models::PatchedWritableVirtualCircuitRequestType>,
    /// * `planned` - Planned * `provisioning` - Provisioning * `active` - Active * `offline` - Offline * `deprovisioning` - Deprovisioning * `decommissioned` - Decommissioned
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(rename = "tenant", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tenant: Option<Option<Box<crate::models::AsnRangeRequestTenant>>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "comments", skip_serializing_if = "Option::is_none")]
    pub comments: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::NestedTagRequest>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl VirtualCircuitRequest {
    /// Adds support for custom fields and tags.
    pub fn new(cid: String, provider_network: crate::models::BriefVirtualCircuitRequestProviderNetwork, r#type: crate::models::PatchedWritableVirtualCircuitRequestType) -> VirtualCircuitRequest {
        VirtualCircuitRequest {
            cid,
            provider_network: Box::new(provider_network),
            provider_account: None,
            r#type: Box::new(r#type),
            status: None,
            tenant: None,
            description: None,
            comments: None,
            tags: None,
            custom_fields: None,
        }
    }
}

/// * `planned` - Planned * `provisioning` - Provisioning * `active` - Active * `offline` - Offline * `deprovisioning` - Deprovisioning * `decommissioned` - Decommissioned
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "planned")]
    Planned,
    #[serde(rename = "provisioning")]
    Provisioning,
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "offline")]
    Offline,
    #[serde(rename = "deprovisioning")]
    Deprovisioning,
    #[serde(rename = "decommissioned")]
    Decommissioned,
}

impl Default for Status {
    fn default() -> Status {
        Self::Planned
    }
}

