/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.7.0-Docker-5.1.1 (4.7)
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VirtualMachineStartOnBoot {
    /// * `on` - On * `off` - Off * `laststate` - Last State
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<Value>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<Label>,
}

impl VirtualMachineStartOnBoot {
    pub fn new() -> VirtualMachineStartOnBoot {
        VirtualMachineStartOnBoot {
            value: None,
            label: None,
        }
    }
}

/// * `on` - On * `off` - Off * `laststate` - Last State
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Value {
    #[serde(rename = "on")]
    On,
    #[serde(rename = "off")]
    Off,
    #[serde(rename = "laststate")]
    Laststate,
}

impl Default for Value {
    fn default() -> Value {
        Self::On
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Label {
    #[serde(rename = "On")]
    On,
    #[serde(rename = "Off")]
    Off,
    #[serde(rename = "Last State")]
    LastState,
}

impl Default for Label {
    fn default() -> Label {
        Self::On
    }
}
