/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.2-Docker-3.4.1 (4.4)
 * 
 * Generated by: https://openapi-generator.tech
 */

/// VlanRequest : Adds support for custom fields and tags.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VlanRequest {
    #[serde(rename = "site", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub site: Option<Option<Box<crate::models::PatchedWritableVlanRequestSite>>>,
    #[serde(rename = "group", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub group: Option<Option<Box<crate::models::PatchedWritableVlanRequestGroup>>>,
    /// Numeric VLAN ID (1-4094)
    #[serde(rename = "vid")]
    pub vid: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "tenant", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tenant: Option<Option<Box<crate::models::AsnRangeRequestTenant>>>,
    /// * `active` - Active * `reserved` - Reserved * `deprecated` - Deprecated
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(rename = "role", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub role: Option<Option<Box<crate::models::IpRangeRequestRole>>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// * `svlan` - Service * `cvlan` - Customer
    #[serde(rename = "qinq_role", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub qinq_role: Option<Option<QinqRole>>,
    #[serde(rename = "qinq_svlan", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub qinq_svlan: Option<Option<Box<crate::models::NestedVlanRequest>>>,
    #[serde(rename = "comments", skip_serializing_if = "Option::is_none")]
    pub comments: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::NestedTagRequest>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl VlanRequest {
    /// Adds support for custom fields and tags.
    pub fn new(vid: i32, name: String) -> VlanRequest {
        VlanRequest {
            site: None,
            group: None,
            vid,
            name,
            tenant: None,
            status: None,
            role: None,
            description: None,
            qinq_role: None,
            qinq_svlan: None,
            comments: None,
            tags: None,
            custom_fields: None,
        }
    }
}

/// * `active` - Active * `reserved` - Reserved * `deprecated` - Deprecated
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "reserved")]
    Reserved,
    #[serde(rename = "deprecated")]
    Deprecated,
}

impl Default for Status {
    fn default() -> Status {
        Self::Active
    }
}
/// * `svlan` - Service * `cvlan` - Customer
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum QinqRole {
    #[serde(rename = "svlan")]
    Svlan,
    #[serde(rename = "cvlan")]
    Cvlan,
    #[serde(rename = "null")]
    Null,
}

impl Default for QinqRole {
    fn default() -> QinqRole {
        Self::Svlan
    }
}

