/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.2-Docker-3.4.1 (4.4)
 * 
 * Generated by: https://openapi-generator.tech
 */

/// VlanTranslationPolicy : Adds support for custom fields and tags.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VlanTranslationPolicy {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "display")]
    pub display: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "rules")]
    pub rules: Vec<crate::models::VlanTranslationRule>,
}

impl VlanTranslationPolicy {
    /// Adds support for custom fields and tags.
    pub fn new(id: i32, url: String, display: String, name: String, rules: Vec<crate::models::VlanTranslationRule>) -> VlanTranslationPolicy {
        VlanTranslationPolicy {
            id,
            url,
            display,
            name,
            description: None,
            rules,
        }
    }
}


