/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.7.1-Docker-5.1.1 (4.7)
 *
 * Generated by: https://openapi-generator.tech
 */

/// VlanTranslationRule : Adds support for custom fields and tags.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VlanTranslationRule {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "display_url", skip_serializing_if = "Option::is_none")]
    pub display_url: Option<String>,
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    #[serde(rename = "policy")]
    pub policy: i32,
    /// Numeric VLAN ID (1-4094)
    #[serde(rename = "local_vid")]
    pub local_vid: i32,
    /// Numeric VLAN ID (1-4094)
    #[serde(rename = "remote_vid")]
    pub remote_vid: i32,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::NestedTag>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(
        rename = "created",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub created: Option<Option<String>>,
    #[serde(
        rename = "last_updated",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_updated: Option<Option<String>>,
}

impl VlanTranslationRule {
    /// Adds support for custom fields and tags.
    pub fn new(policy: i32, local_vid: i32, remote_vid: i32) -> VlanTranslationRule {
        VlanTranslationRule {
            id: None,
            url: None,
            display_url: None,
            display: None,
            policy,
            local_vid,
            remote_vid,
            description: None,
            tags: None,
            custom_fields: None,
            created: None,
            last_updated: None,
        }
    }
}
